sudo: required
services:
  - docker
matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      cache:
        yarn: true
        directories:
          - "node_modules"
          - "packages/react-native-oursky/node_modules"
          - "packages/react-native-oursky-example/node_modules"
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn
      script:
        - yarn format
        - yarn flow
